#!/usr/bin/env python

def build(bld):
    bld.program(
            packages = 'curses',
            target = 'tsge-adventure',
            use = 'GLIB GOBJECT CURSES',
            source = 'main.vala',
        )

